require "active_support"

require_relative "temporal/application_versioning"
require_relative "temporal/as_of_query"
require_relative "temporal/as_of_query/association_macros"
require_relative "temporal/as_of_query/association_scope"
require_relative "temporal/as_of_query/association_walker"
require_relative "temporal/as_of_query/predicate_builder/handlers"
require_relative "temporal/as_of_query/query_methods"
require_relative "temporal/as_of_query/scope_registry"
require_relative "temporal/as_of_query/time_dimensions"
require_relative "temporal/patches/association_reflection"
require_relative "temporal/patches/join_dependency"
require_relative "temporal/patches/merger"
require_relative "temporal/patches/relation"
require_relative "temporal/patches/through_association"
require_relative "temporal/system_versioning"
require_relative "temporal/system_versioning/command_recorder"
require_relative "temporal/system_versioning/namespace"
require_relative "temporal/system_versioning/model"
require_relative "temporal/system_versioning/schema_creation"
require_relative "temporal/system_versioning/schema_definitions"
require_relative "temporal/system_versioning/schema_statements"

ActiveSupport.on_load(:active_record) do
  require "active_record/connection_adapters/postgresql_adapter" # TODO: add test

  ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.include(ActiveRecord::Temporal::SystemVersioning::SchemaStatements)
  ActiveRecord::Migration::CommandRecorder.include(ActiveRecord::Temporal::SystemVersioning::CommandRecorder)
  ActiveRecord::Relation.include(ActiveRecord::Temporal::AsOfQuery::QueryMethods)

  # Patches

  # Patches the `build_arel` method wrap itself in the as-of query scope registry.
  # This is what allows temporal association scopes to be aware of the time-scope
  # value of the relation that included them.
  #
  # Patches the `instantiate_records` method to call `initialize_time_scope_from_relation`
  # on each loaded record.
  ActiveRecord::Relation.prepend(ActiveRecord::Temporal::Patches::Relation)

  # Patches the `merge` method (called by `Relation#merge`) to handle the new
  # query method `time_scope` that this gem adds.
  ActiveRecord::Relation::Merger.prepend(ActiveRecord::Temporal::Patches::Merger)

  # Patches the preloader's `through_scope` method to pass along the relation's
  # time-scope values when it handles has-many-through associations. The handler
  # for has-many assoication uses `Relation#merge`, but this one doesn't.
  ActiveRecord::Associations::Preloader::ThroughAssociation.prepend(ActiveRecord::Temporal::Patches::ThroughAssociation)

  # This permits association scopes generated by this gem to be eager-load if they
  # are "optionally instance-dependent." That is to say, they accept arguments,
  # but don't require any arguments.
  #
  # I think permitting eager-loading optionally instance-dependent association
  # scopes would make sense as a general feature. See this PR for my justification:
  # https://github.com/rails/rails/pull/56004
  ActiveRecord::Reflection::AssociationReflection.prepend(ActiveRecord::Temporal::Patches::AssociationReflection)

  # This is a copy of a fix from https://github.com/rails/rails/pull/56088 that
  # impacts this gem. I has been backported to supported stable versions of
  # Active Record, but until those patches are released it's included here.
  ActiveRecord::Associations::JoinDependency.prepend(ActiveRecord::Temporal::Patches::JoinDependency)
end
