module ActiveRecord::Temporal
  module Patches
    # This permits association scopes generated by this gem to be eager-load if
    # they are "optionally instance-dependent." That is to say, they accept but
    # don't require arguments.
    #
    # I think permitting eager-loading of such scopes would make sense as a
    # standalone feature for Active Record. See this PR for my justification:
    # https://github.com/rails/rails/pull/56004
    module AssociationReflection
      def check_eager_loadable!
        super unless temporal_scope? && scope_requires_no_params?
      end

      private

      def temporal_scope?
        scope.respond_to?(:temporal_scope?) && scope.temporal_scope?
      end

      def scope_requires_no_params?
        scope.arity == 0 || scope.arity == -1
      end
    end
  end
end
